const languages = {
  "EN": {
    "Header": {
      "Dashboard": "Dashboard",
      "Mattress": "Mattress",
      "Types": "Types",
      "Group": "Group"
    },
    "Login": {
      "WelcomeToMatcron!": "Welcome to Matcron!",
      "EnterEmail": "Enter email",
      "EnterPassword": "Enter password",
      "ForgotPassword": "Forgot Password",
      "LogIn": "Log In",
      "WelcomeBack": "Welcome Back"
    },
    "Dashboard": {
      "MattressLifecycle": "Mattress Lifecycle",
      "MattressMaintenance": "Mattress Maintenance",
      "RequesWash": "Request Wash"
    },
    "Mattress": {
      "ImportGroup": "Import Group",
      "PreviewName": "Name",
      "PreviewDesc": "Description",
      "PreviewCount": "Mattress Count",
      "PreviewStatus": "Status",
      "PreviewPurpose": "Transfer Purpose",
      "PreviewCancel": "Cancel",
      "PreviewImport": "Import",
      "ImportSuccess": "Mattresses imported successfully!",
      "MattressAddedToGroup": "Mattresses added to group successfully!",
      "MattressAlreadyAdded": "Mattresses already added to group.",
      "FilterByStatus": "Filter by Status",
      "SearchMattress": "Search Mattress",
      "TypeHeader": "Type",
      "LocationHeader": "Location",
      "StatusHeader": "Status",
      "NoMattress": "No mattresses available",
      "Rotate": "Rotate",
      "Days": "days",
      "EndOfLifecycle": "End of Lifecycle",
      "Organization": "Organization",
      "MattressEdit": "Edit",
      "MattressMore": "More",
      "AddMattressTitle": "Mattress",
      "EnterLocation": "Enter Location",
      "SelectMattressType": "Search Mattress Type",
      "AddCustomType": "+ Add custom type",
      "SelectDate": "Select Date",
      "Generate RFID": "Generate RFID",
      "ErrorWrtiting": "Error while writing to badge",
      "NotWritable": "Tag is not writable",
      "TapRFID": "Tap On Mattress RFID...",
      "Processing": "Processing...",
      "FinishhedWriting": "Finished writing to NFC tag!",
      "FailedWriting": "Failed or no writable tag found.",
      "In Production": "In Production",
      "In Inventory": "In Inventory",
      "Assigned": "Assigned",
      "In Use": "In Use",
      "Cleaning Required": "Cleaning Required",
      "Decommissoned": "Decommissioned",
      "In Transit": "In Transit",
    },
    "Type": {
      "SearchType": "Search Mattress Type",
      "AddType": "+ Add Type",
      "TypeHeader": "Type",
      "InchesHeader": "Inches",
      "StockHeader": "Stock",
      "Edit": "Edit",
      "Delete": "Delete",
    },
    "Profile": {
      "Help": "Help",
      "Account": "Account",
      "Terms": "Terms and Conditions",
      "Notifications": "Notifications",
      "Organization": "Organization",
      "Reports": "Reports",
      "Security": "Security",
      "Settings": "Settings",
      "Language": "Change Language",
      "About": "About Us",
      "Log Out": "Log Out"
    }
  },
  "DE": {
    "Header": {
      "Dashboard": "Dashboard",
      "Mattress": "Matratze",
      "Types": "Typen",
      "Group": "Gruppe"
    },
    "Login": {
      "WelcomeToMatcron!": "Willkommen bei Matcron!",
      "EnterEmail": "E-Mail eingeben",
      "EnterPassword": "Passwort eingeben",
      "ForgotPassword": "Passwort vergessen",
      "LogIn": "Einloggen",
      "WelcomeBack": "Willkommen zurück"
    },
    "Dashboard": {
      "MattressLifecycle": "Matratzenlebenszyklus",
      "MattressMaintenance": "Matratzenwartung",
      "RequesWash": "Wäsche anfordern"
    },
    "Mattress": {
      "ImportGroup": "Gruppe importieren",
      "PreviewName": "Name",
      "PreviewDesc": "Beschreibung",
      "PreviewCount": "Matratzenanzahl",
      "PreviewStatus": "Status",
      "PreviewPurpose": "Transferzweck",
      "PreviewCancel": "Abbrechen",
      "PreviewImport": "Importieren",
      "ImportSuccess": "Matratzen erfolgreich importiert!",
      "MattressAddedToGroup": "Matratzen erfolgreich zur Gruppe hinzugefügt!",
      "MattressAlreadyAdded": "Matratzen bereits zur Gruppe hinzugefügt.",
      "FilterByStatus": "Nach Status filtern",
      "SearchMattress": "Matratze suchen",
      "TypeHeader": "Typ",
      "LocationHeader": "Ort",
      "StatusHeader": "Status",
      "NoMattress": "Keine Matratzen verfügbar",
      "Rotate": "Drehen",
      "Days": "Tage",
      "EndOfLifecycle": "Ende des Lebenszyklus",
      "Organization": "Organisation",
      "MattressEdit": "Bearbeiten",
      "MattressMore": "Mehr",
      "AddMattressTitle": "Matratze",
      "EnterLocation": "Ort eingeben",
      "SelectMattressType": "Matratzentyp suchen",
      "AddCustomType": "+ Benutzerdefinierten Typ hinzufügen",
      "SelectDate": "Datum auswählen",
      "Generate RFID": "RFID generieren",
      "ErrorWrtiting": "Fehler beim Schreiben auf das Abzeichen",
      "NotWritable": "Tag ist nicht beschreibbar",
      "TapRFID": "Tippen Sie auf Matratzen-RFID...",
      "Processing": "Verarbeitung...",
      "FinishhedWriting": "Schreiben auf NFC-Tag abgeschlossen!",
      "FailedWriting": "Fehlgeschlagen oder kein beschreibbarer Tag gefunden.",

      //STATUSUES
      "In Production": "In Produktion",
      "In Inventory": "Im Lager",
      "Assigned": "Zugewiesen",
      "In Use": "In Gebrauch",
      "Cleaning Required": "Reinigung erforderlich",
      "Decommissioned": "Außer Dienst gestellt",
      "In Transit": "Im Transit"
    },
    "Type": {
      "SearchType": "Matratzentyp suchen",
      "AddType": "+ Typ hinzufügen",
      "TypeHeader": "Typ",
      "InchesHeader": "Zoll",
      "StockHeader": "Bestand",
      "Edit": "Bearbeiten",
      "Delete": "Löschen"
    },
    "Profile": {
      "Help": "Hilfe",
      "Account": "Konto",
      "Terms": "Allgemeine Geschäftsbedingungen",
      "Notifications": "Benachrichtigungen",
      "Organization": "Organisation",
      "Reports": "Berichte",
      "Security": "Sicherheit",
      "Settings": "Einstellungen",
      "Language": "Sprache ändern",
      "About": "Über uns",
      "Log Out": "Abmelden"
    }

  },
  "ES": {
    "Header": {
      "Dashboard": "Tablero",
      "Mattress": "Colchón",
      "Types": "Tipos",
      "Group": "Grupo"
    },
    "Login": {
      "WelcomeToMatcron!": "¡Bienvenido a Matcron!",
      "EnterEmail": "Ingresar correo electrónico",
      "EnterPassword": "Ingresar contraseña",
      "ForgotPassword": "¿Olvidaste tu contraseña?",
      "LogIn": "Iniciar sesión",
      "WelcomeBack": "Bienvenido de nuevo"
    },
    "Dashboard": {
      "MattressLifecycle": "Ciclo de vida del colchón",
      "MattressMaintenance": "Mantenimiento del colchón",
      "RequesWash": "Solicitar lavado"
    },
    "Mattress": {
      "ImportGroup": "Importar grupo",
      "PreviewName": "Nombre",
      "PreviewDesc": "Descripción",
      "PreviewCount": "Cantidad de colchones",
      "PreviewStatus": "Estado",
      "PreviewPurpose": "Propósito de transferencia",
      "PreviewCancel": "Cancelar",
      "PreviewImport": "Importar",
      "ImportSuccess": "¡Colchones importados con éxito!",
      "MattressAddedToGroup": "¡Colchones añadidos al grupo con éxito!",
      "MattressAlreadyAdded": "Colchones ya añadidos al grupo.",
      "FilterByStatus": "Filtrar por estado",
      "SearchMattress": "Buscar colchón",
      "TypeHeader": "Tipo",
      "LocationHeader": "Ubicación",
      "StatusHeader": "Estado",
      "NoMattress": "No hay colchones disponibles",
      "Rotate": "Rotar",
      "Days": "días",
      "EndOfLifecycle": "Fin del ciclo de vida",
      "Organization": "Organización",
      "MattressEdit": "Editar",
      "MattressMore": "Más",
      "AddMattressTitle": "Colchón",
      "EnterLocation": "Ingresar ubicación",
      "SelectMattressType": "Buscar tipo de colchón",
      "AddCustomType": "+ Agregar tipo personalizado",
      "SelectDate": "Seleccionar fecha",
      "Generate RFID": "Generar RFID",
      "ErrorWrtiting": "Error al escribir en la etiqueta",
      "NotWritable": "La etiqueta no es escribible",
      "TapRFID": "Toca la etiqueta RFID del colchón...",
      "Processing": "Procesando...",
      "FinishhedWriting": "¡Escritura en etiqueta NFC completada!",
      "FailedWriting": "Falló o no se encontró una etiqueta escribible.",
      "In Production": "En producción",
      "In Inventory": "En inventario",
      "Assigned": "Asignado",
      "In Use": "En uso",
      "Cleaning Required": "Limpieza requerida",
      "Decommissioned": "Fuera de servicio",
      "In Transit": "En tránsito"
    },

    "Type": {
      "SearchType": "Buscar tipo de colchón",
      "AddType": "+ Agregar tipo",
      "TypeHeader": "Tipo",
      "InchesHeader": "Pulgadas",
      "StockHeader": "Stock",
      "Edit": "Editar",
      "Delete": "Eliminar"
    },
    "Profile": {
      "Help": "Ayuda",
      "Account": "Cuenta",
      "Terms": "Términos y condiciones",
      "Notifications": "Notificaciones",
      "Organization": "Organización",
      "Reports": "Informes",
      "Security": "Seguridad",
      "Settings": "Configuración",
      "Language": "Cambiar idioma",
      "About": "Sobre nosotros",
      "Log Out": "Cerrar sesión"
    }

  }
};
