const languages = {
  "EN": {
    "Header": {
      "Dashboard": "Dashboard",
      "Mattress": "Mattress",
      "Types": "Types",
      "Group": "Group"
    },
    "Login": {
      "WelcomeToMatcron!": "Welcome to Matcron!",
      "EnterEmail": "Enter email",
      "EnterPassword": "Enter password",
      "ForgotPassword": "Forgot Password",
      "LogIn": "Log In",
      "WelcomeBack": "Welcome Back"
    },
    "Dashboard": {
      "MattressLifecycle": "Mattress Lifecycle",
      "MattressMaintenance": "Mattress Maintenance",
      "RequesWash": "Request Wash"
    },
    "Mattress": {
      "ImportGroup": "Import Group",
      "PreviewName": "Name",
      "PreviewDesc": "Description",
      "PreviewCount": "Mattress Count",
      "PreviewStatus": "Status",
      "PreviewPurpose": "Transfer Purpose",
      "PreviewCancel": "Cancel",
      "PreviewImport": "Import",
      "ImportSuccess": "Mattresses imported successfully!",
      "MattressAddedToGroup": "Mattresses added to group successfully!",
      "MattressAlreadyAdded": "Mattresses already added to group.",
      "FilterByStatus": "Filter by Status",
      "SearchMattress": "Search Mattress",
      "TypeHeader": "Type",
      "LocationHeader": "Location",
      "StatusHeader": "Status",
      "NoMattress": "No mattresses available",
      "Rotate": "Rotate",
      "Days": "days",
      "EndOfLifecycle": "End of Lifecycle",
      "Organization": "Organization",
      "MattressEdit": "Edit",
      "MattressMore": "More",
      "AddMattressTitle": "Mattress",
      "EnterLocation": "Enter Location",
      "SelectMattressType": "Search Mattress Type",
      "AddCustomType": "+ Add custom type",
      "SelectDate": "Select Date",
      "Generate RFID": "Generate RFID",
      "ErrorWrtiting": "Error while writing to badge",
      "NotWritable": "Tag is not writable",
      "TapRFID": "Tap On Mattress RFID...",
      "Processing": "Processing...",
      "FinishhedWriting": "Finished writing to NFC tag!",
      "FailedWriting": "Failed or no writable tag found.",
      "In Production": "In Production",
      "In Inventory": "In Inventory",
      "Assigned": "Assigned",
      "In Use": "In Use",
      "Cleaning Required": "Cleaning Required",
      "Decommissioned": "Decommissioned",
      "In Transit": "In Transit",
    },
    "Type": {
      "SearchType": "Search Mattress Type",
      "AddType": "+ Add Type",
      "TypeHeader": "Type",
      "InchesHeader": "Inches",
      "StockHeader": "Stock",
      "Edit": "Edit",
      "Delete": "Delete",
    },
    "Profile": {
      "Help": "Help",
      "Account": "Account",
      "Terms": "Terms and Conditions",
      "Notifications": "Notifications",
      "Organization": "Organization",
      "Reports": "Reports",
      "Security": "Security",
      "Settings": "Settings",
      "Language": "Change Language",
      "About": "About Us",
      "Log Out": "Log Out"
    },
    "Group": {
      "SearchGroups": "Search groups",
      "Add": "Add",
      "Active": "Active",
      "Archived": "Archived",
      "Mattresses": "mattresses"
    }
  },
  "DE": {
    "Header": {
      "Dashboard": "Dashboard",
      "Mattress": "Matratze",
      "Types": "Typen",
      "Group": "Gruppe"
    },
    "Login": {
      "WelcomeToMatcron!": "Willkommen bei Matcron!",
      "EnterEmail": "E-Mail eingeben",
      "EnterPassword": "Passwort eingeben",
      "ForgotPassword": "Passwort vergessen",
      "LogIn": "Einloggen",
      "WelcomeBack": "Willkommen zurück"
    },
    "Dashboard": {
      "MattressLifecycle": "Matratzenlebenszyklus",
      "MattressMaintenance": "Matratzenwartung",
      "RequesWash": "Wäsche anfordern"
    },
    "Mattress": {
      "ImportGroup": "Gruppe importieren",
      "PreviewName": "Name",
      "PreviewDesc": "Beschreibung",
      "PreviewCount": "Matratzenanzahl",
      "PreviewStatus": "Status",
      "PreviewPurpose": "Transferzweck",
      "PreviewCancel": "Abbrechen",
      "PreviewImport": "Importieren",
      "ImportSuccess": "Matratzen erfolgreich importiert!",
      "MattressAddedToGroup": "Matratzen erfolgreich zur Gruppe hinzugefügt!",
      "MattressAlreadyAdded": "Matratzen bereits zur Gruppe hinzugefügt.",
      "FilterByStatus": "Nach Status filtern",
      "SearchMattress": "Matratze suchen",
      "TypeHeader": "Typ",
      "LocationHeader": "Ort",
      "StatusHeader": "Status",
      "NoMattress": "Keine Matratzen verfügbar",
      "Rotate": "Drehen",
      "Days": "Tage",
      "EndOfLifecycle": "Ende des Lebenszyklus",
      "Organization": "Organisation",
      "MattressEdit": "Bearbeiten",
      "MattressMore": "Mehr",
      "AddMattressTitle": "Matratze",
      "EnterLocation": "Ort eingeben",
      "SelectMattressType": "Matratzentyp suchen",
      "AddCustomType": "+ Benutzerdefinierten Typ hinzufügen",
      "SelectDate": "Datum auswählen",
      "Generate RFID": "RFID generieren",
      "ErrorWrtiting": "Fehler beim Schreiben auf das Abzeichen",
      "NotWritable": "Tag ist nicht beschreibbar",
      "TapRFID": "Tippen Sie auf Matratzen-RFID...",
      "Processing": "Verarbeitung...",
      "FinishhedWriting": "Schreiben auf NFC-Tag abgeschlossen!",
      "FailedWriting": "Fehlgeschlagen oder kein beschreibbarer Tag gefunden.",

      //STATUSUES
      "In Production": "In Produktion",
      "In Inventory": "Im Lager",
      "Assigned": "Zugewiesen",
      "In Use": "In Gebrauch",
      "Cleaning Required": "Reinigung erforderlich",
      "Decommissioned": "Außer Dienst gestellt",
      "In Transit": "Im Transit"
    },
    "Type": {
      "SearchType": "Matratzentyp suchen",
      "AddType": "+ Typ hinzufügen",
      "TypeHeader": "Typ",
      "InchesHeader": "Zoll",
      "StockHeader": "Bestand",
      "Edit": "Bearbeiten",
      "Delete": "Löschen"
    },
    "Profile": {
      "Help": "Hilfe",
      "Account": "Konto",
      "Terms": "Allgemeine Geschäftsbedingungen",
      "Notifications": "Benachrichtigungen",
      "Organization": "Organisation",
      "Reports": "Berichte",
      "Security": "Sicherheit",
      "Settings": "Einstellungen",
      "Language": "Sprache ändern",
      "About": "Über uns",
      "Log Out": "Abmelden"
    },
    "Group": {
      "SearchGroups": "Gruppen suchen",
      "Add": "Hinzufügen",
      "Active": "Aktiv",
      "Archived": "Archiviert",
      "Mattresses": "Matratzen"
    }
  },
  "ES": {
    "Header": {
      "Dashboard": "Tablero",
      "Mattress": "Colchón",
      "Types": "Tipos",
      "Group": "Grupo"
    },
    "Login": {
      "WelcomeToMatcron!": "¡Bienvenido a Matcron!",
      "EnterEmail": "Ingresar correo electrónico",
      "EnterPassword": "Ingresar contraseña",
      "ForgotPassword": "¿Olvidaste tu contraseña?",
      "LogIn": "Iniciar sesión",
      "WelcomeBack": "Bienvenido de nuevo"
    },
    "Dashboard": {
      "MattressLifecycle": "Ciclo de vida del colchón",
      "MattressMaintenance": "Mantenimiento del colchón",
      "RequesWash": "Solicitar lavado"
    },
    "Mattress": {
      "ImportGroup": "Importar grupo",
      "PreviewName": "Nombre",
      "PreviewDesc": "Descripción",
      "PreviewCount": "Cantidad de colchones",
      "PreviewStatus": "Estado",
      "PreviewPurpose": "Propósito de transferencia",
      "PreviewCancel": "Cancelar",
      "PreviewImport": "Importar",
      "ImportSuccess": "¡Colchones importados con éxito!",
      "MattressAddedToGroup": "¡Colchones añadidos al grupo con éxito!",
      "MattressAlreadyAdded": "Colchones ya añadidos al grupo.",
      "FilterByStatus": "Filtrar por estado",
      "SearchMattress": "Buscar colchón",
      "TypeHeader": "Tipo",
      "LocationHeader": "Ubicación",
      "StatusHeader": "Estado",
      "NoMattress": "No hay colchones disponibles",
      "Rotate": "Rotar",
      "Days": "días",
      "EndOfLifecycle": "Fin del ciclo de vida",
      "Organization": "Organización",
      "MattressEdit": "Editar",
      "MattressMore": "Más",
      "AddMattressTitle": "Colchón",
      "EnterLocation": "Ingresar ubicación",
      "SelectMattressType": "Buscar tipo de colchón",
      "AddCustomType": "+ Agregar tipo personalizado",
      "SelectDate": "Seleccionar fecha",
      "Generate RFID": "Generar RFID",
      "ErrorWrtiting": "Error al escribir en la etiqueta",
      "NotWritable": "La etiqueta no es escribible",
      "TapRFID": "Toca la etiqueta RFID del colchón...",
      "Processing": "Procesando...",
      "FinishhedWriting": "¡Escritura en etiqueta NFC completada!",
      "FailedWriting": "Falló o no se encontró una etiqueta escribible.",
      "In Production": "En producción",
      "In Inventory": "En inventario",
      "Assigned": "Asignado",
      "In Use": "En uso",
      "Cleaning Required": "Limpieza requerida",
      "Decommissioned": "Fuera de servicio",
      "In Transit": "En tránsito"
    },
    "Type": {
      "SearchType": "Buscar tipo de colchón",
      "AddType": "+ Agregar tipo",
      "TypeHeader": "Tipo",
      "InchesHeader": "Pulgadas",
      "StockHeader": "Stock",
      "Edit": "Editar",
      "Delete": "Eliminar"
    },
    "Profile": {
      "Help": "Ayuda",
      "Account": "Cuenta",
      "Terms": "Términos y condiciones",
      "Notifications": "Notificaciones",
      "Organization": "Organización",
      "Reports": "Informes",
      "Security": "Seguridad",
      "Settings": "Configuración",
      "Language": "Cambiar idioma",
      "About": "Sobre nosotros",
      "Log Out": "Cerrar sesión"
    },
    "Group": {
      "SearchGroups": "Buscar grupos",
      "Add": "Agregar",
      "Active": "Activo",
      "Archived": "Archivado",
      "Mattresses": "Colchones"
    }
  },
  "FR": {
    "Header": {
      "Dashboard": "Tableau de bord",
      "Mattress": "Matelas",
      "Types": "Types",
      "Group": "Groupe"
    },
    "Login": {
      "WelcomeToMatcron!": "Bienvenue sur Matcron !",
      "EnterEmail": "Entrez votre e-mail",
      "EnterPassword": "Entrez votre mot de passe",
      "ForgotPassword": "Mot de passe oublié",
      "LogIn": "Se connecter",
      "WelcomeBack": "Bon retour"
    },
    "Dashboard": {
      "MattressLifecycle": "Cycle de vie du matelas",
      "MattressMaintenance": "Entretien du matelas",
      "RequesWash": "Demander un lavage"
    },
    "Mattress": {
      "ImportGroup": "Importer un groupe",
      "PreviewName": "Nom",
      "PreviewDesc": "Description",
      "PreviewCount": "Nombre de matelas",
      "PreviewStatus": "Statut",
      "PreviewPurpose": "But du transfert",
      "PreviewCancel": "Annuler",
      "PreviewImport": "Importer",
      "ImportSuccess": "Matelas importés avec succès !",
      "MattressAddedToGroup": "Matelas ajoutés au groupe avec succès !",
      "MattressAlreadyAdded": "Les matelas sont déjà ajoutés au groupe.",
      "FilterByStatus": "Filtrer par statut",
      "SearchMattress": "Rechercher un matelas",
      "TypeHeader": "Type",
      "LocationHeader": "Emplacement",
      "StatusHeader": "Statut",
      "NoMattress": "Aucun matelas disponible",
      "Rotate": "Faire pivoter",
      "Days": "jours",
      "EndOfLifecycle": "Fin du cycle de vie",
      "Organization": "Organisation",
      "MattressEdit": "Modifier",
      "MattressMore": "Plus",
      "AddMattressTitle": "Matelas",
      "EnterLocation": "Entrer l'emplacement",
      "SelectMattressType": "Rechercher un type de matelas",
      "AddCustomType": "+ Ajouter un type personnalisé",
      "SelectDate": "Sélectionner une date",
      "Generate RFID": "Générer RFID",
      "ErrorWrtiting": "Erreur lors de l’écriture sur le badge",
      "NotWritable": "Tag non inscriptible",
      "TapRFID": "Approchez le RFID du matelas...",
      "Processing": "Traitement...",
      "FinishhedWriting": "Écriture terminée sur le tag NFC !",
      "FailedWriting": "Échec ou aucun tag inscriptible trouvé.",
      "In Production": "En production",
      "In Inventory": "En inventaire",
      "Assigned": "Attribué",
      "In Use": "En cours d'utilisation",
      "Cleaning Required": "Nettoyage requis",
      "Decommissoned": "Mis hors service",
      "In Transit": "En transit"
    },
    "Type": {
      "SearchType": "Rechercher un type de matelas",
      "AddType": "+ Ajouter un type",
      "TypeHeader": "Type",
      "InchesHeader": "Pouces",
      "StockHeader": "Stock",
      "Edit": "Modifier",
      "Delete": "Supprimer"
    },
    "Profile": {
      "Help": "Aide",
      "Account": "Compte",
      "Terms": "Termes et conditions",
      "Notifications": "Notifications",
      "Organization": "Organisation",
      "Reports": "Rapports",
      "Security": "Sécurité",
      "Settings": "Paramètres",
      "Language": "Changer de langue",
      "About": "À propos de nous",
      "Log Out": "Se déconnecter"
    },
    "Group": {
      "SearchGroups": "Rechercher des groupes",
      "Add": "Ajouter",
      "Active": "Actif",
      "Archived": "Archivé",
      "Mattresses": "Matelas"
    }
  },
  "IT": {
    "Header": {
      "Dashboard": "Cruscotto",
      "Mattress": "Materasso",
      "Types": "Tipi",
      "Group": "Gruppo"
    },
    "Login": {
      "WelcomeToMatcron!": "Benvenuto su Matcron!",
      "EnterEmail": "Inserisci l'email",
      "EnterPassword": "Inserisci la password",
      "ForgotPassword": "Password dimenticata",
      "LogIn": "Accedi",
      "WelcomeBack": "Bentornato"
    },
    "Dashboard": {
      "MattressLifecycle": "Ciclo di vita del materasso",
      "MattressMaintenance": "Manutenzione del materasso",
      "RequesWash": "Richiedi lavaggio"
    },
    "Mattress": {
      "ImportGroup": "Importa gruppo",
      "PreviewName": "Nome",
      "PreviewDesc": "Descrizione",
      "PreviewCount": "Numero di materassi",
      "PreviewStatus": "Stato",
      "PreviewPurpose": "Scopo del trasferimento",
      "PreviewCancel": "Annulla",
      "PreviewImport": "Importa",
      "ImportSuccess": "Materassi importati con successo!",
      "MattressAddedToGroup": "Materassi aggiunti al gruppo con successo!",
      "MattressAlreadyAdded": "I materassi sono già stati aggiunti al gruppo.",
      "FilterByStatus": "Filtra per stato",
      "SearchMattress": "Cerca materasso",
      "TypeHeader": "Tipo",
      "LocationHeader": "Posizione",
      "StatusHeader": "Stato",
      "NoMattress": "Nessun materasso disponibile",
      "Rotate": "Ruota",
      "Days": "giorni",
      "EndOfLifecycle": "Fine del ciclo di vita",
      "Organization": "Organizzazione",
      "MattressEdit": "Modifica",
      "MattressMore": "Altro",
      "AddMattressTitle": "Materasso",
      "EnterLocation": "Inserisci posizione",
      "SelectMattressType": "Cerca tipo di materasso",
      "AddCustomType": "+ Aggiungi tipo personalizzato",
      "SelectDate": "Seleziona data",
      "Generate RFID": "Genera RFID",
      "ErrorWrtiting": "Errore durante la scrittura sul badge",
      "NotWritable": "Tag non scrivibile",
      "TapRFID": "Avvicina il RFID del materasso...",
      "Processing": "Elaborazione...",
      "FinishhedWriting": "Scrittura completata sul tag NFC!",
      "FailedWriting": "Errore o nessun tag scrivibile trovato.",
      "In Production": "In produzione",
      "In Inventory": "In inventario",
      "Assigned": "Assegnato",
      "In Use": "In uso",
      "Cleaning Required": "Pulizia necessaria",
      "Decommissoned": "Fuori servizio",
      "In Transit": "In transito"
    },
    "Type": {
      "SearchType": "Cerca tipo di materasso",
      "AddType": "+ Aggiungi tipo",
      "TypeHeader": "Tipo",
      "InchesHeader": "Pollici",
      "StockHeader": "Stock",
      "Edit": "Modifica",
      "Delete": "Elimina"
    },
    "Profile": {
      "Help": "Aiuto",
      "Account": "Account",
      "Terms": "Termini e condizioni",
      "Notifications": "Notifiche",
      "Organization": "Organizzazione",
      "Reports": "Report",
      "Security": "Sicurezza",
      "Settings": "Impostazioni",
      "Language": "Cambia lingua",
      "About": "Chi siamo",
      "Log Out": "Esci"
    },
    "Group": {
      "SearchGroups": "Cerca gruppi",
      "Add": "Aggiungi",
      "Active": "Attivo",
      "Archived": "Archiviato",
      "Mattresses": "Materassi"
    }
  },
  "NL": {
    "Header": {
      "Dashboard": "Dashboard",
      "Mattress": "Matras",
      "Types": "Typen",
      "Group": "Groep"
    },
    "Login": {
      "WelcomeToMatcron!": "Welkom bij Matcron!",
      "EnterEmail": "Voer e-mailadres in",
      "EnterPassword": "Voer wachtwoord in",
      "ForgotPassword": "Wachtwoord vergeten",
      "LogIn": "Inloggen",
      "WelcomeBack": "Welkom terug"
    },
    "Dashboard": {
      "MattressLifecycle": "Matras levenscyclus",
      "MattressMaintenance": "Matras onderhoud",
      "RequesWash": "Wasbeurt aanvragen"
    },
    "Mattress": {
      "ImportGroup": "Groep importeren",
      "PreviewName": "Naam",
      "PreviewDesc": "Beschrijving",
      "PreviewCount": "Aantal matrassen",
      "PreviewStatus": "Status",
      "PreviewPurpose": "Doel van overdracht",
      "PreviewCancel": "Annuleren",
      "PreviewImport": "Importeren",
      "ImportSuccess": "Matrassen succesvol geïmporteerd!",
      "MattressAddedToGroup": "Matrassen succesvol aan de groep toegevoegd!",
      "MattressAlreadyAdded": "Matrassen zijn al aan de groep toegevoegd.",
      "FilterByStatus": "Filter op status",
      "SearchMattress": "Zoek matras",
      "TypeHeader": "Type",
      "LocationHeader": "Locatie",
      "StatusHeader": "Status",
      "NoMattress": "Geen matrassen beschikbaar",
      "Rotate": "Draaien",
      "Days": "dagen",
      "EndOfLifecycle": "Einde levenscyclus",
      "Organization": "Organisatie",
      "MattressEdit": "Bewerken",
      "MattressMore": "Meer",
      "AddMattressTitle": "Matras",
      "EnterLocation": "Voer locatie in",
      "SelectMattressType": "Zoek matras type",
      "AddCustomType": "+ Aangepast type toevoegen",
      "SelectDate": "Selecteer datum",
      "Generate RFID": "Genereer RFID",
      "ErrorWrtiting": "Fout bij schrijven naar badge",
      "NotWritable": "Tag is niet beschrijfbaar",
      "TapRFID": "Houd de matras RFID tegen...",
      "Processing": "Bezig...",
      "FinishhedWriting": "Schrijven naar NFC-tag voltooid!",
      "FailedWriting": "Mislukt of geen beschrijfbare tag gevonden.",
      "In Production": "In productie",
      "In Inventory": "Op voorraad",
      "Assigned": "Toegewezen",
      "In Use": "In gebruik",
      "Cleaning Required": "Reiniging vereist",
      "Decommissoned": "Buiten gebruik gesteld",
      "In Transit": "Onderweg"
    },
    "Type": {
      "SearchType": "Zoek matras type",
      "AddType": "+ Type toevoegen",
      "TypeHeader": "Type",
      "InchesHeader": "Inches",
      "StockHeader": "Voorraad",
      "Edit": "Bewerken",
      "Delete": "Verwijderen"
    },
    "Profile": {
      "Help": "Help",
      "Account": "Account",
      "Terms": "Voorwaarden",
      "Notifications": "Meldingen",
      "Organization": "Organisatie",
      "Reports": "Rapporten",
      "Security": "Beveiliging",
      "Settings": "Instellingen",
      "Language": "Taal wijzigen",
      "About": "Over ons",
      "Log Out": "Uitloggen"
    },
    "Group": {
      "SearchGroups": "Groepen zoeken",
      "Add": "Toevoegen",
      "Active": "Actief",
      "Archived": "Gearchiveerd",
      "Mattresses": "Matrassen"
    }
  },
  "PT": {
    "Header": {
      "Dashboard": "Painel de Controle",
      "Mattress": "Colchão",
      "Types": "Tipos",
      "Group": "Grupo"
    },
    "Login": {
      "WelcomeToMatcron!": "Bem-vindo ao Matcron!",
      "EnterEmail": "Insira o e-mail",
      "EnterPassword": "Insira a senha",
      "ForgotPassword": "Esqueceu a senha?",
      "LogIn": "Entrar",
      "WelcomeBack": "Bem-vindo de volta"
    },
    "Dashboard": {
      "MattressLifecycle": "Ciclo de Vida do Colchão",
      "MattressMaintenance": "Manutenção do Colchão",
      "RequesWash": "Solicitar Lavagem"
    },
    "Mattress": {
      "ImportGroup": "Importar Grupo",
      "PreviewName": "Nome",
      "PreviewDesc": "Descrição",
      "PreviewCount": "Quantidade de Colchões",
      "PreviewStatus": "Status",
      "PreviewPurpose": "Finalidade da Transferência",
      "PreviewCancel": "Cancelar",
      "PreviewImport": "Importar",
      "ImportSuccess": "Colchões importados com sucesso!",
      "MattressAddedToGroup": "Colchões adicionados ao grupo com sucesso!",
      "MattressAlreadyAdded": "Os colchões já foram adicionados ao grupo.",
      "FilterByStatus": "Filtrar por Status",
      "SearchMattress": "Buscar Colchão",
      "TypeHeader": "Tipo",
      "LocationHeader": "Localização",
      "StatusHeader": "Status",
      "NoMattress": "Nenhum colchão disponível",
      "Rotate": "Girar",
      "Days": "dias",
      "EndOfLifecycle": "Fim do Ciclo de Vida",
      "Organization": "Organização",
      "MattressEdit": "Editar",
      "MattressMore": "Mais",
      "AddMattressTitle": "Colchão",
      "EnterLocation": "Insira a Localização",
      "SelectMattressType": "Buscar Tipo de Colchão",
      "AddCustomType": "+ Adicionar Tipo Personalizado",
      "SelectDate": "Selecionar Data",
      "Generate RFID": "Gerar RFID",
      "ErrorWrtiting": "Erro ao escrever no crachá",
      "NotWritable": "Tag não pode ser escrita",
      "TapRFID": "Aproxime o RFID do Colchão...",
      "Processing": "Processando...",
      "FinishhedWriting": "Escrita concluída na tag NFC!",
      "FailedWriting": "Falha ou nenhuma tag gravável encontrada.",
      "In Production": "Em Produção",
      "In Inventory": "Em Estoque",
      "Assigned": "Atribuído",
      "In Use": "Em Uso",
      "Cleaning Required": "Limpeza Necessária",
      "Decommissoned": "Desativado",
      "In Transit": "Em Trânsito"
    },
    "Type": {
      "SearchType": "Buscar Tipo de Colchão",
      "AddType": "+ Adicionar Tipo",
      "TypeHeader": "Tipo",
      "InchesHeader": "Polegadas",
      "StockHeader": "Estoque",
      "Edit": "Editar",
      "Delete": "Excluir"
    },
    "Profile": {
      "Help": "Ajuda",
      "Account": "Conta",
      "Terms": "Termos e Condições",
      "Notifications": "Notificações",
      "Organization": "Organização",
      "Reports": "Relatórios",
      "Security": "Segurança",
      "Settings": "Configurações",
      "Language": "Alterar Idioma",
      "About": "Sobre Nós",
      "Log Out": "Sair"
    },
    "Group": {
      "SearchGroups": "Pesquisar grupos",
      "Add": "Adicionar",
      "Active": "Ativo",
      "Archived": "Arquivado",
      "Mattresses": "Colchões"
    }
  },
  "AR": {
    "Header": {
      "Dashboard": "لوحة التحكم",
      "Mattress": "المرتبة",
      "Types": "الأنواع",
      "Group": "المجموعة"
    },
    "Login": {
      "WelcomeToMatcron!": "مرحبًا بك في ماتكرون!",
      "EnterEmail": "أدخل البريد الإلكتروني",
      "EnterPassword": "أدخل كلمة المرور",
      "ForgotPassword": "هل نسيت كلمة المرور؟",
      "LogIn": "تسجيل الدخول",
      "WelcomeBack": "مرحبًا بعودتك"
    },
    "Dashboard": {
      "MattressLifecycle": "دورة حياة المرتبة",
      "MattressMaintenance": "صيانة المرتبة",
      "RequesWash": "طلب الغسيل"
    },
    "Mattress": {
      "ImportGroup": "استيراد المجموعة",
      "PreviewName": "الاسم",
      "PreviewDesc": "الوصف",
      "PreviewCount": "عدد المراتب",
      "PreviewStatus": "الحالة",
      "PreviewPurpose": "الغرض من النقل",
      "PreviewCancel": "إلغاء",
      "PreviewImport": "استيراد",
      "ImportSuccess": "تم استيراد المراتب بنجاح!",
      "MattressAddedToGroup": "تمت إضافة المراتب إلى المجموعة بنجاح!",
      "MattressAlreadyAdded": "تمت إضافة المراتب بالفعل إلى المجموعة.",
      "FilterByStatus": "تصفية حسب الحالة",
      "SearchMattress": "البحث عن مرتبة",
      "TypeHeader": "النوع",
      "LocationHeader": "الموقع",
      "StatusHeader": "الحالة",
      "NoMattress": "لا توجد مراتب متاحة",
      "Rotate": "تدوير",
      "Days": "أيام",
      "EndOfLifecycle": "نهاية دورة الحياة",
      "Organization": "المؤسسة",
      "MattressEdit": "تعديل",
      "MattressMore": "المزيد",
      "AddMattressTitle": "مرتبة",
      "EnterLocation": "أدخل الموقع",
      "SelectMattressType": "ابحث عن نوع المرتبة",
      "AddCustomType": "+ إضافة نوع مخصص",
      "SelectDate": "حدد التاريخ",
      "Generate RFID": "إنشاء RFID",
      "ErrorWrtiting": "خطأ أثناء الكتابة على البطاقة",
      "NotWritable": "العلامة غير قابلة للكتابة",
      "TapRFID": "المس علامة RFID الخاصة بالمرتبة...",
      "Processing": "جارٍ المعالجة...",
      "FinishhedWriting": "تمت الكتابة إلى علامة NFC بنجاح!",
      "FailedWriting": "فشل أو لم يتم العثور على علامة قابلة للكتابة.",
      "In Production": "قيد الإنتاج",
      "In Inventory": "في المخزون",
      "Assigned": "مخصص",
      "In Use": "قيد الاستخدام",
      "Cleaning Required": "يتطلب التنظيف",
      "Decommissoned": "متوقف عن الخدمة",
      "In Transit": "قيد النقل"
    },
    "Type": {
      "SearchType": "البحث عن نوع المرتبة",
      "AddType": "+ إضافة نوع",
      "TypeHeader": "النوع",
      "InchesHeader": "البوصات",
      "StockHeader": "المخزون",
      "Edit": "تعديل",
      "Delete": "حذف"
    },
    "Profile": {
      "Help": "المساعدة",
      "Account": "الحساب",
      "Terms": "الشروط والأحكام",
      "Notifications": "الإشعارات",
      "Organization": "المؤسسة",
      "Reports": "التقارير",
      "Security": "الأمان",
      "Settings": "الإعدادات",
      "Language": "تغيير اللغة",
      "About": "معلومات عنا",
      "Log Out": "تسجيل الخروج"
    },
    "Group": {
      "SearchGroups": "البحث عن المجموعات",
      "Add": "إضافة",
      "Active": "نشط",
      "Archived": "مؤرشف",
      "Mattresses": "مراتب"
    }
  }
};