name: matcron
description: "A new Flutter project for managing mattress tracking."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the app.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # For iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Launcher icons for app icon configuration
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/MATCRON_Logo.png"
# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets section for organizing images and icons
  assets:
    - assets/images/MATCRON_Logo.png

