name: matcron
description: "A new Flutter project for managing mattress tracking."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the app.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3

  # For iOS-style icons
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  retrofit: ^4.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  crypt: ^4.3.1
  animated_notch_bottom_bar: ^1.0.0
  crypto: ^3.0.6
  encrypt: ^5.0.3
  flutter_secure_storage: ^8.1.0
  nfc_manager: ^3.5.0
  intl: ^0.20.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  retrofit_generator: ^9.1.5


  # Launcher icons for app icon configuration
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/MATCRON_Logo.png"
# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets section for organizing images and icons
  assets:
    - assets/images/MATCRON_Logo.png
    - assets/images/profile_image.png
    - assets/images/bed.jpg
    - assets/images/login_pic.png
    - assets/images/globe.png
    - assets/images/handshake.jpg
    - assets/images/hearts.jpg
    - assets/images/recycle.jpeg
    - assets/images/redheart.png
    - assets/images/Screwdriver.png
    - assets/images/fabric-roll.jpg
    - assets/images/mattress1.jpg
    - assets/images/bedmeasuring.png
    - assets/images/box.png
    - assets/images/group.png
    - assets/images/single.png
    - assets/images/vs.png
    - assets/images/rfid.png
    - assets/images/add.png
    - assets/images/import.png
    - assets/images/transfer.png
    - assets/images/assign_page.png
    - assets/images/scan_icon.png