name: matcron
description: "A new Flutter project for managing mattress tracking."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version and build number for the app.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # For iOS-style icons
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  retrofit: ^4.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  crypt: ^4.3.1
  animated_notch_bottom_bar: ^1.0.0
  crypto: ^3.0.6
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  retrofit_generator: ^9.1.5


  # Launcher icons for app icon configuration
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/MATCRON_Logo.png"
# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Assets section for organizing images and icons
  assets:
    - assets/images/MATCRON_Logo.png
    - assets/images/profile_image.png

