name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up the Dart SDK
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      # Specify the working directory for the app location
      - name: Install dependencies
        run: dart pub get
        working-directory: Matcron-Frontend/matcron

      # Uncomment to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .
      #   working-directory: Matcron-Frontend/matcron

      - name: Analyze project source
        run: dart analyze
        working-directory: Matcron-Frontend/matcron

      - name: Run tests
        run: dart test
        working-directory: Matcron-Frontend/matcron
