name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # You can specify a version here, e.g., '2.10.0'

      # Specify the working directory for the app location
      - name: Install dependencies
        run: flutter pub get
        working-directory: Matcron-Frontend/matcron

      # Uncomment to verify the use of 'flutter format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .
      #   working-directory: Matcron-Frontend/matcron

      - name: Analyze project source
        run: flutter analyze
        working-directory: Matcron-Frontend/matcron

      - name: Run tests
        run: flutter test
        working-directory: Matcron-Frontend/matcron
